---
abstract: 'A Shutdown Daemon'
author:
  - 'Robin Clarke <perl@robinclarke.net>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Daemon-Shutdown
no_index:
  directory:
    - t
    - inc
requires:
  AnyEvent: 0
  File::Basename: 0
  Getopt::Long: 0
  IPC::Run: 0
  Log::Log4perl: 0
  Params::Validate: 0
  Pod::Usage: 0
  Test::More: 0
  Try::Tiny: 0
  User: 0
  YAML::Any: 0
version: 0.09
